#include <stdint.h>

// DATA FROM REMOTE
int8_t ANGLE_DESIRED;
int8_t SPEED_DESIRED;

// METRICS
uint16_t DISTANCE_MEASURED;
int16_t SPEED_MEASURED_ACC;
int16_t RPM_MEASURED_MAG;
int16_t RPM_MEASURED_OPT;
int16_t SPEED_MEASURED;
int16_t PITCH;
int16_t ROLL;
uint8_t BATTERY_CHARGE;

// FLAGS
uint8_t MALFUNCTION;
uint8_t CONNECTED;
uint8_t DATA_VALID_FLAGS;

